name: TokenTest

on:
  push: {}
  pull_request:
    branches: [ add-workflow_dispatch-ci-pipeline ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
    - name: Without GITHUB_TOKEN env var
      shell: pwsh
      continue-on-error: true
      run: |
        $headers = @{
            Accept     = 'application/vnd.github.v3+json'
        }

        $null = irm -Uri "https://api.github.com/repos/Jaykul/FromGithub/releases/latest" -Headers $headers -ResponseHeadersVariable respheaders
        Write-Host "Rate Limit Remaining: $($respheaders."X-RateLimit-Remaining")"


    - name: With GITHUB_TOKEN env var
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $headers = @{
            Accept     = 'application/vnd.github.v3+json'
        }
        if( $env:GITHUB_TOKEN ) {
            $headers.Authorization = "bearer $($Env:GITHUB_TOKEN)"
        }

        $null = irm -Uri "https://api.github.com/repos/Jaykul/FromGithub/releases/latest" -Headers $headers -ResponseHeadersVariable respheaders
        Write-Host "Rate Limit Remaining: $($respheaders."X-RateLimit-Remaining")"
